version: '2'

networks:
  votty:

services:
  ca.init.votty.net:
    image: hyperledger/fabric-ca:1.2.1
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.init.votty.net
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.init.votty.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/8700dd8071e02dcfd60d21c65af05f7e44d40fd8a1d6c38ed103cecd22d6ad0b_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/init.votty.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.init
    networks:
        - votty

  peers.votty.net:
    container_name: peers.votty.net
    image: hyperledger/fabric-orderer:1.2.1
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/composer-genesis.block
      - ORDERER_GENERAL_LOCALMSPID=PeersMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/votty.net/orderers/peers.votty.net/msp:/etc/hyperledger/msp/orderer/msp
    networks:
        - votty

  d1.init.votty.net:
    container_name: d1.init.votty.net
    image: hyperledger/fabric-peer:1.2.1
    environment:
      - CORE_LOGGING_LEVEL=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=d1.init.votty.net
      - CORE_PEER_ADDRESS=d1.init.votty.net:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=composer_votty
      - CORE_PEER_LOCALMSPID=InitPeerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=votty-db:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/init.votty.net/peers/d1.init.votty.net/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/init.votty.net/users:/etc/hyperledger/msp/users
    networks:
        - votty
    depends_on:
      - peers.votty.net
      - votty-db

  votty-db:
    container_name: votty-db
    image: hyperledger/fabric-couchdb:0.4.10
    ports:
      - 5984:5984
    environment:
      DB_URL: http://localhost:5984/member_db
    networks:
        - votty

  votty-cli:
    container_name: votty-cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=votty-operator
      - CORE_PEER_ADDRESS=d1.init.votty.net:7051
      - CORE_PEER_LOCALMSPID=InitPeerMSP
      - CORE_PEER_MSPCONFIGPATH=/peer/crypto/peerOrganizations/init.votty.net/users/Admin@init.votty.net/msp
      - CORE_CHAINCODE_KEEPALIVE=10
      - CORE_PEER_CHAINCODELISTENADDRESS=d1.init.votty.net:7051
      - CORE_PEER_ADDRESSAUTODETECT=true
    working_dir: /peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config:/peer/crypto/
        - /vty/peer/:/peer/cc/
        - /vty/net/cs/chaincode/fabcar/node/:/peer/fabcar/
    networks:
        - votty
